(() => {
'use strict';
const VERSION='6.2.1',KEY='bishunGeneralizationV61', $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
let data=null,state; try{state=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{state={}} state={missions:{},contrasts:{},external:[],...state};
const save=()=>localStorage.setItem(KEY,JSON.stringify(state)); const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function score(){const m=Object.values(state.missions).filter(Boolean).length,c=Object.values(state.contrasts).filter(Boolean).length,e=state.external.length;return Math.min(99,Math.round((m/data.missions.length*45)+(c/data.registerContrasts.length*20)+(Math.min(e,12)/12*35)));}
function render(){if(!data)return; $('[data-generalization-version]')?.replaceChildren(document.createTextNode(VERSION)); $('#g61Score').textContent=score()+'%'; $('#g61MissionCount').textContent=`${Object.values(state.missions).filter(Boolean).length} / ${data.missions.length}`; $('#g61ContrastCount').textContent=`${Object.values(state.contrasts).filter(Boolean).length} / ${data.registerContrasts.length}`; $('#g61ExternalCount').textContent=state.external.length;
const domain=$('#g61Domain')?.value||'all'; const list=data.missions.filter(x=>domain==='all'||x.domain===domain).slice(0,18); $('#g61MissionGrid').innerHTML=list.map(x=>`<article class="g61-card ${state.missions[x.id]?'done':''}"><small>${esc(x.domain)} · ${esc(x.level)}</small><h3>${esc(x.taskPt)}</h3><ul>${x.evidence.map(e=>`<li>${esc(e)}</li>`).join('')}</ul><button type="button" data-g61-mission="${x.id}">${state.missions[x.id]?'Evidência registrada':'Registrar evidência'}</button></article>`).join('');
$('#g61ContrastGrid').innerHTML=data.registerContrasts.slice(0,24).map(x=>`<article class="g61-contrast ${state.contrasts[x.id]?'done':''}"><div><b>${x.a}</b><span>${esc(x.aPt)}</span></div><div><b>${x.b}</b><span>${esc(x.bPt)}</span></div><p>${esc(x.evidencePt)}</p><button type="button" data-g61-contrast="${x.id}">${state.contrasts[x.id]?'Concluído':'Marcar contraste'}</button></article>`).join('');}
function analyze(){const text=$('#g61ExternalText').value.trim(); if(!text){$('#g61ExternalResult').textContent='Cole um material externo.';return;} const chars=[...text].filter(c=>/[㐀-鿿]/.test(c)); const uniq=new Set(chars); const rec={date:new Date().toISOString(),chars:chars.length,unique:uniq.size,source:$('#g61Source').value.trim(),self:Number($('#g61SelfScore').value||0)};state.external.push(rec);save();$('#g61ExternalResult').innerHTML=`<strong>Evidência externa registrada.</strong> ${chars.length} caracteres chineses, ${uniq.size} distintos, autoavaliação ${rec.self}%. A autoavaliação não substitui correção independente.`;render();}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.g61Mission){state.missions[b.dataset.g61Mission]=!state.missions[b.dataset.g61Mission];save();render()}if(b.dataset.g61Contrast){state.contrasts[b.dataset.g61Contrast]=!state.contrasts[b.dataset.g61Contrast];save();render()}if(b.id==='g61Analyze')analyze();});
fetch('data/generalization-v61.json').then(r=>r.json()).then(d=>{data=d;const sel=$('#g61Domain');sel.innerHTML='<option value="all">Todos os domínios</option>'+data.domains.map(x=>`<option>${esc(x.name)}</option>`).join('');sel.addEventListener('change',render);render();}).catch(()=>{$('#g61Status').textContent='Falha ao carregar a camada de generalização.'});
})();
