(() => {
  'use strict';
  const VERSION = '6.2.0';
  const KEY = 'bishunMasteryV6';
  const SKILLS = ['reading','dictation','cloze','shadowing','production','transfer'];
  const LABELS = {reading:'Leitura inédita',dictation:'Ditado',cloze:'Cloze contextual',shadowing:'Shadowing',production:'Produção livre',transfer:'Transferência'};
  const $ = (s,r=document) => r.querySelector(s);
  const $$ = (s,r=document) => [...r.querySelectorAll(s)];
  const esc = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
  const today=()=>new Date().toISOString().slice(0,10);
  const defaultState=()=>({evidence:Object.fromEntries(SKILLS.map(k=>[k,[]])),currentId:null,mode:'reading',plans:[],created:Date.now()});
  let state;
  try { state={...defaultState(),...JSON.parse(localStorage.getItem(KEY)||'{}')}; } catch { state=defaultState(); }
  state.evidence ||= defaultState().evidence;
  SKILLS.forEach(k=>state.evidence[k] ||= []);
  let data=null,current=null,dictationIndex=0;

  function save(){localStorage.setItem(KEY,JSON.stringify(state));}
  function normalize(s=''){return String(s).normalize('NFKC').toLowerCase().replace(/[\s，。！？；：、,.!?;:'"“”‘’（）()《》<>【】\[\]—…-]/g,'');}
  function editDistance(a,b){a=[...normalize(a)];b=[...normalize(b)];const row=Array(b.length+1).fill(0).map((_,i)=>i);for(let i=1;i<=a.length;i++){let prev=row[0];row[0]=i;for(let j=1;j<=b.length;j++){const old=row[j];row[j]=Math.min(row[j]+1,row[j-1]+1,prev+(a[i-1]===b[j-1]?0:1));prev=old;}}return row[b.length];}
  function similarity(a,b){const aa=normalize(a),bb=normalize(b),m=Math.max([...aa].length,[...bb].length);return m?Math.round((1-editDistance(aa,bb)/m)*100):0;}
  function speak(text,rate=.82){if(!('speechSynthesis' in window))return; speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(text);u.lang='zh-CN';u.rate=rate;const vs=speechSynthesis.getVoices();u.voice=vs.find(v=>v.lang.toLowerCase()==='zh-cn')||vs.find(v=>v.lang.toLowerCase().startsWith('zh'))||null;speechSynthesis.speak(u);}
  function addEvidence(skill,score,mode=current?.id,meta={}){const item={ts:Date.now(),date:today(),score:clamp(Math.round(score),0,100),benchmark:current?.id||mode,genre:current?.genre||'',level:current?.level||'',...meta};state.evidence[skill].unshift(item);state.evidence[skill]=state.evidence[skill].slice(0,200);save();renderDashboard();renderMatrix();setStatus(`${LABELS[skill]} registrada: ${item.score}%.`);}
  function skillScore(skill){const a=state.evidence[skill]||[];if(!a.length)return 0;const recent=a.slice(0,8);const weights=recent.map((_,i)=>Math.max(1,8-i));return Math.round(recent.reduce((s,x,i)=>s+x.score*weights[i],0)/weights.reduce((a,b)=>a+b,0));}
  function skillDays(skill){return new Set((state.evidence[skill]||[]).map(x=>x.date)).size;}
  function evidenceCount(){return SKILLS.reduce((s,k)=>s+state.evidence[k].length,0);}
  function allDays(){return new Set(SKILLS.flatMap(k=>state.evidence[k].map(x=>x.date))).size;}
  function allGenres(){return new Set(SKILLS.flatMap(k=>state.evidence[k].map(x=>x.genre).filter(Boolean))).size;}
  function eligible(){return SKILLS.every(k=>state.evidence[k].length>=3&&skillDays(k)>=2)&&allGenres()>=4;}
  function overall(){if(!eligible())return null;const vals=SKILLS.map(skillScore).map(x=>Math.max(1,x));return Math.min(99,Math.round(Math.exp(vals.reduce((s,x)=>s+Math.log(x),0)/vals.length)));}
  function setStatus(t){if($('#masteryV6Status'))$('#masteryV6Status').textContent=t;}
  function renderDashboard(){
    const o=overall();
    $('#v6Overall').textContent=o===null?'—':`${o}%`;
    $('#v6EvidenceCount').textContent=evidenceCount().toLocaleString('pt-BR');
    $('#v6SessionDays').textContent=allDays();
    $('#v6GenreCount').textContent=`${allGenres()} / 12`;
    $('#v6Eligibility').textContent=o===null?'Índice bloqueado: são necessárias 3 evidências por competência, em pelo menos 2 dias, e 4 gêneros diferentes.':'Índice longitudinal liberado; o máximo exibido é 99%, pois nenhuma amostra certifica domínio absoluto.';
    $('#v6EvidenceGrid').innerHTML=SKILLS.map(k=>{const s=skillScore(k),n=state.evidence[k].length,d=skillDays(k);return `<article class="v6-skill-card"><span>${LABELS[k]}</span><strong>${n?s+'%':'—'}</strong><div><i style="width:${s}%"></i></div><small>${n} evidência${n===1?'':'s'} · ${d} dia${d===1?'':'s'}</small></article>`;}).join('');
  }
  function completedBenchmark(id){const rows=SKILLS.flatMap(k=>state.evidence[k].filter(x=>x.benchmark===id));return rows.length>=3&&new Set(rows.map(x=>x.date)).size>=1&&rows.reduce((s,x)=>s+x.score,0)/rows.length>=75;}
  function renderMatrix(){if(!data)return;const genres=[...new Set(data.benchmarks.map(x=>x.genre))],levels=['intermediário','avançado','superior'];$('#v6Matrix').innerHTML=`<div class="v6-matrix-head"><b>Gênero</b>${levels.map(l=>`<b>${l}</b>`).join('')}</div>`+genres.map(g=>`<div class="v6-matrix-row"><strong>${esc(g)}</strong>${levels.map(l=>{const x=data.benchmarks.find(b=>b.genre===g&&b.level===l),done=x&&completedBenchmark(x.id);return `<button type="button" data-v6-open="${x?.id||''}" class="${done?'done':''}" title="Abrir ${esc(g)}, ${l}">${done?'✓':'○'}</button>`;}).join('')}</div>`).join('');}
  function filtered(){const g=$('#v6Genre')?.value||'all',l=$('#v6Level')?.value||'all';return data.benchmarks.filter(x=>(g==='all'||x.genre===g)&&(l==='all'||x.level===l));}
  function choose(id=null){const pool=filtered();if(!pool.length)return;current=id?data.benchmarks.find(x=>x.id===id):pool[Math.floor(Math.random()*pool.length)];if(!current)current=pool[0];state.currentId=current.id;save();dictationIndex=Math.floor(Math.random()*2);renderBenchmark();renderExercise();}
  function renderBenchmark(){if(!current)return;$('#v6BenchmarkCard').innerHTML=`<div class="v6-benchmark-meta"><span>${esc(current.genre)}</span><span>${esc(current.level)}</span><span>${current.id}</span></div><h3>${esc(current.titlePt)}</h3><p class="v6-zh" lang="zh-Hans">${current.zh}</p><div class="v6-benchmark-actions"><button type="button" data-v6-speak="${esc(current.zh)}">🔊 Ouvir texto</button><button type="button" id="v6AnalyzeImmersion">Analisar no laboratório lexical</button></div><details><summary>Resumo e palavras-chave</summary><p>${esc(current.summaryPt)}</p><div class="v6-keywords">${current.keywords.map(x=>`<span>${esc(x)}</span>`).join('')}</div></details>`;}
  function modeButton(mode){return `<button type="button" data-v6-mode="${mode}" class="${state.mode===mode?'active':''}">${LABELS[mode]}</button>`;}
  function renderModeTabs(){$('#v6ModeTabs').innerHTML=SKILLS.map(modeButton).join('');}
  function qHTML(q,i){return `<fieldset class="v6-question"><legend>${i+1}. ${esc(q.qPt)}</legend>${q.optionsPt.map((o,j)=>`<label><input type="radio" name="v6q${i}" value="${j}"> ${esc(o)}</label>`).join('')}</fieldset>`;}
  function rubric(prefix,labels){return `<div class="v6-rubric-input">${labels.map((x,i)=>`<label>${esc(x)}<select id="${prefix}${i}"><option value="0">0 · insuficiente</option><option value="1">1 · parcial</option><option value="2">2 · consistente</option></select></label>`).join('')}</div>`;}
  function renderExercise(){if(!current)return;renderModeTabs();let h='';
    if(state.mode==='reading')h=`<p>Leia sem consultar o resumo e responda.</p>${current.questions.map(qHTML).join('')}<button type="button" id="v6CheckReading" class="button primary">Corrigir compreensão</button>`;
    if(state.mode==='cloze')h=`<p class="v6-cloze" lang="zh-Hans">${esc(current.cloze.sentence)}</p><label>Complete o trecho<input id="v6ClozeInput" lang="zh-Hans" autocomplete="off"></label><button type="button" id="v6CheckCloze" class="button primary">Verificar cloze</button>`;
    if(state.mode==='dictation'){const s=current.dictation[dictationIndex];h=`<p>Ouça sem olhar a resposta e escreva em caracteres.</p><button type="button" class="v6-audio-large" data-v6-speak="${esc(s)}" data-v6-slow="1">▶ Reproduzir ditado</button><textarea id="v6DictationInput" lang="zh-Hans" rows="3" placeholder="Digite o que ouviu"></textarea><button type="button" id="v6CheckDictation" class="button primary">Comparar ditado</button>`;}
    if(state.mode==='shadowing'){const s=current.dictation[dictationIndex];h=`<p>Ouça, repita imediatamente e preserve ritmo, tons e pausas.</p><p class="v6-shadow-text" lang="zh-Hans">${esc(s)}</p><div class="v6-action-row"><button type="button" data-v6-speak="${esc(s)}">▶ Velocidade normal</button><button type="button" data-v6-speak="${esc(s)}" data-v6-slow="1">▶ Lento</button><button type="button" id="v6Recognize">🎙 Reconhecimento de voz</button></div><p id="v6SpeechResult">O reconhecimento depende do navegador. Sem reconhecimento, a autoavaliação é limitada a 70%.</p><div class="v6-self"><button data-v6-shadow="35">Preciso repetir</button><button data-v6-shadow="55">Parcial</button><button data-v6-shadow="70">Consistente</button></div>`;}
    if(state.mode==='production')h=`<p><strong>Tarefa:</strong> ${esc(current.productionPt)}</p><textarea id="v6ProductionText" lang="zh-Hans" rows="7" placeholder="Produza sem copiar o texto-base"></textarea><div id="v6ProductionCount">0 caracteres chineses</div>${rubric('v6Prod',['Clareza','Gramática','Vocabulário','Coesão','Adequação ao gênero'])}<button type="button" id="v6SaveProduction" class="button primary">Registrar produção</button>`;
    if(state.mode==='transfer')h=`<p>Reformule o conteúdo como outro gênero: aviso, mensagem, resumo técnico, explicação leiga ou argumento.</p><label>Gênero de destino<select id="v6TargetGenre"><option>aviso público</option><option>mensagem informal</option><option>resumo técnico</option><option>explicação leiga</option><option>argumento crítico</option></select></label><textarea id="v6TransferText" lang="zh-Hans" rows="7" placeholder="Reescreva em chinês"></textarea>${rubric('v6Trans',['Fidelidade ao conteúdo','Mudança de registro','Naturalidade','Organização'])}<button type="button" id="v6SaveTransfer" class="button primary">Registrar transferência</button>`;
    $('#v6Exercise').innerHTML=h;$('#v6Feedback').innerHTML='';}
  function feedback(ok,title,detail){$('#v6Feedback').innerHTML=`<div class="v6-feedback ${ok?'ok':'bad'}"><strong>${esc(title)}</strong><p>${esc(detail)}</p></div>`;}
  function checkReading(){let correct=0,answered=0;current.questions.forEach((q,i)=>{const v=$(`input[name="v6q${i}"]:checked`);if(v){answered++;if(Number(v.value)===q.answer)correct++;}});if(answered<current.questions.length){feedback(false,'Responda todas as questões','Nenhuma evidência foi registrada.');return;}const score=Math.round(correct/current.questions.length*100);addEvidence('reading',score,current.id,{correct,total:current.questions.length});feedback(score>=75,`${correct}/${current.questions.length} respostas corretas`,score>=75?'Compreensão registrada.':'Releia o texto antes de tentar novamente.');}
  function checkCloze(){const v=$('#v6ClozeInput').value,score=similarity(v,current.cloze.answer);addEvidence('cloze',score,current.id,{answer:v});feedback(score>=85,`Similaridade: ${score}%`,`Resposta esperada: ${current.cloze.answer}`);}
  function checkDictation(){const expected=current.dictation[dictationIndex],v=$('#v6DictationInput').value,score=similarity(v,expected);addEvidence('dictation',score,current.id,{answer:v});feedback(score>=85,`Precisão: ${score}%`,`Texto esperado: ${expected}`);dictationIndex=(dictationIndex+1)%2;}
  function startRecognition(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$('#v6SpeechResult').textContent='Reconhecimento indisponível; use a autoavaliação limitada.';return;}const expected=current.dictation[dictationIndex],r=new SR();r.lang='zh-CN';r.interimResults=false;r.maxAlternatives=3;$('#v6SpeechResult').textContent='Ouvindo…';r.onresult=e=>{const candidates=[...e.results[0]].map(x=>x.transcript),best=Math.max(...candidates.map(x=>similarity(x,expected)));$('#v6SpeechResult').textContent=`Reconhecido: ${candidates[0]} · similaridade ${best}%`;addEvidence('shadowing',best,current.id,{recognized:candidates[0],automatic:true});};r.onerror=e=>{$('#v6SpeechResult').textContent=`Falha no reconhecimento: ${e.error}`;};r.start();}
  function chineseCount(s){return ([...String(s)].filter(c=>/[\u3400-\u9fff]/u.test(c))).length;}
  function rubricScore(prefix,n){let sum=0;for(let i=0;i<n;i++)sum+=Number($(`#${prefix}${i}`)?.value||0);return Math.round(sum/(n*2)*100);}
  function saveProduction(){const text=$('#v6ProductionText').value.trim(),count=chineseCount(text);if(count<40){feedback(false,'Produção curta',`Foram detectados ${count} caracteres chineses; o mínimo para evidência é 40.`);return;}const self=rubricScore('v6Prod',5),score=Math.min(85,Math.round(self*.75+Math.min(100,count/1.2)*.25));addEvidence('production',score,current.id,{chars:count,text});feedback(score>=70,`Produção registrada: ${score}%`,'A autoavaliação é limitada a 85%; revisão externa continua necessária.');}
  function saveTransfer(){const text=$('#v6TransferText').value.trim(),count=chineseCount(text);if(count<35){feedback(false,'Transferência curta',`Foram detectados ${count} caracteres; o mínimo é 35.`);return;}const self=rubricScore('v6Trans',4),score=Math.min(85,Math.round(self*.8+Math.min(100,count/1.1)*.2));addEvidence('transfer',score,current.id,{chars:count,text,target:$('#v6TargetGenre').value});feedback(score>=70,`Transferência registrada: ${score}%`,'Pontuação limitada a 85% sem avaliação externa.');}
  function weakest(){return [...SKILLS].sort((a,b)=>skillScore(a)-skillScore(b));}
  function generatePlan(){const mins=Number($('#v6PlannerMinutes').value||180),weak=weakest(),sessions=Math.max(3,Math.round(mins/45));const genres=[...new Set(data.benchmarks.map(x=>x.genre))];const weeks=Array.from({length:12},(_,i)=>{const focus=[weak[i%6],weak[(i+1)%6]],g1=genres[i%genres.length],g2=genres[(i+5)%genres.length];return {week:i+1,focus,g1,g2,sessions,minutes:mins};});state.plans.unshift({ts:Date.now(),minutes:mins,weeks});state.plans=state.plans.slice(0,5);save();$('#v6Plan').innerHTML=weeks.map(w=>`<article><span>Semana ${w.week}</span><strong>${LABELS[w.focus[0]]} + ${LABELS[w.focus[1]]}</strong><p>${esc(w.g1)} e ${esc(w.g2)} · ${w.sessions} sessões · ${w.minutes} min</p></article>`).join('');}
  function exportProgress(){const blob=new Blob([JSON.stringify({schema:'bishun-mastery-v6',version:VERSION,exportedAt:new Date().toISOString(),state},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`bishun-dominio-v6-${today()}.json`;a.click();URL.revokeObjectURL(a.href);}
  async function importProgress(file){const obj=JSON.parse(await file.text());if(obj.schema!=='bishun-mastery-v6'||!obj.state)throw new Error('Arquivo incompatível.');state={...defaultState(),...obj.state};state.evidence ||= defaultState().evidence;SKILLS.forEach(k=>state.evidence[k] ||= []);save();renderDashboard();renderMatrix();setStatus('Evidências importadas.');}
  function bind(){
    $('#v6Genre').addEventListener('change',()=>choose());$('#v6Level').addEventListener('change',()=>choose());$('#v6NewBenchmark').addEventListener('click',()=>choose());$('#v6GeneratePlan').addEventListener('click',generatePlan);$('#v6Export').addEventListener('click',exportProgress);$('#v6Import').addEventListener('change',async e=>{try{if(e.target.files?.[0])await importProgress(e.target.files[0]);}catch(err){setStatus(err.message);}e.target.value='';});
    document.addEventListener('input',e=>{if(e.target.id==='v6ProductionText')$('#v6ProductionCount').textContent=`${chineseCount(e.target.value)} caracteres chineses`;});
    document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.v6Speak!==undefined)speak(b.dataset.v6Speak,b.dataset.v6Slow ? .58 : .82);if(b.dataset.v6Mode){state.mode=b.dataset.v6Mode;save();renderExercise();}if(b.dataset.v6Open)choose(b.dataset.v6Open);if(b.id==='v6CheckReading')checkReading();if(b.id==='v6CheckCloze')checkCloze();if(b.id==='v6CheckDictation')checkDictation();if(b.id==='v6Recognize')startRecognition();if(b.dataset.v6Shadow)addEvidence('shadowing',Number(b.dataset.v6Shadow),current.id,{automatic:false});if(b.id==='v6SaveProduction')saveProduction();if(b.id==='v6SaveTransfer')saveTransfer();if(b.id==='v6AnalyzeImmersion'){const t=$('#immersionText');if(t){t.value=current.zh;$('#analyzeImmersion')?.click();$('#imersao-aberta')?.scrollIntoView({behavior:'smooth'});}}});
  }
  async function init(){if(!$('#validacao-v6'))return;try{const r=await fetch('./data/mastery-v6.json',{cache:'no-cache'});if(!r.ok)throw new Error(`${r.status} ao carregar dados v6`);data=await r.json();document.documentElement.dataset.masteryVersion=VERSION;$$('[data-mastery-version]').forEach(x=>x.textContent=VERSION);const genres=[...new Set(data.benchmarks.map(x=>x.genre))];$('#v6Genre').innerHTML='<option value="all">Todos os 12 gêneros</option>'+genres.map(g=>`<option>${esc(g)}</option>`).join('');$('#v6Level').innerHTML='<option value="all">Todos os níveis</option><option>intermediário</option><option>avançado</option><option>superior</option>';bind();renderDashboard();renderMatrix();choose(state.currentId);setStatus('Validação longitudinal pronta. Nenhum percentual global é liberado sem evidência suficiente.');}catch(err){console.error(err);setStatus(`Falha ao iniciar a validação: ${err.message}`);}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
